services:
  rclone:
    image: rclone/rclone:1.66
    container_name: rclone
    command: rcd --rc-web-gui --rc-addr :5572 --rc-htpasswd /config/rclone/.htpasswd
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - PHP_TZ=America/Chicago
      - PUID=1000
      - PGID=1000
    volumes:
      - ./config:/config/rclone
      - ./sync_files:/etc/periodic/15min/sync_files # this will be run by cron
      - /mnt/drive:/data:ro
    networks:
      - swarmnet

networks:
  swarmnet:
    external: true
    driver: overlay