---
version: "3.9"

services:
  notes:
    build:
      context: .
      dockerfile: Dockerfile
    image: notes-code-server:4.23.1
    container_name: notes
    hostname: notes
    restart: unless-stopped
    environment:
      - DOCKER_USER=$USER
    volumes:
      - ./.config:/home/coder/.config
      - /mnt/syncthing/hqt:/home/coder/project
      - local:/home/coder/.local/share/code-server
      - conda_envs:/opt/conda/envs
      - conda_pkgs:/opt/conda/pkgs
    networks:
      - swarmnet # port 8080

networks:
  swarmnet:
    external: true
    driver: overlay

volumes:
  conda_envs:
  conda_pkgs:
  local: