---
version: "3.9"

services:
  cloudflared:
    image: msnelling/cloudflared:2022.5.1
    container_name: cloudflared
    # interpolate environment vars into config template to make config and then run
    command: [sh, -c, ( echo "cat <<EOF" ; cat /etc/cloudflared/config.yml.template ; echo EOF ) | sh > /etc/cloudflare>    volumes:
      - ./config:/etc/cloudflared
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
     - cloudflared
    restart: always

networks:
  cloudflared:
    external: true