services:
  komodo-core:
    image: ghcr.io/mbecker20/komodo:latest
    container_name: komodo-core
    restart: unless-stopped
    env_file: .env
    environment:
      KOMODO_DATABASE_ADDRESS: komodo-mongo:27017
      KOMODO_DATABASE_USERNAME: ${DB_USERNAME}
      KOMODO_DATABASE_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ~/selfhosted/data/komodo/repo-cache:/repo-cache
      - ~/selfhosted/data/komodo/syncs:/syncs
    networks:
      - swarmnet # upstreams 9120
      - komodonet
    labels:
      komodo.skip: # Prevent Komodo from stopping with StopAllContainers
    depends_on:
      - komodo-mongo

  komodo-mongo:
    image: mongo
    container_name: komodo-mongo
    command: --quiet --wiredTigerCacheSizeGB 0.25
    restart: unless-stopped
    volumes:
      - ~/selfhosted/data/komodo/db:/data/db
      - ~/selfhosted/data/komodo/config:/data/configdb
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
    networks:
      - komodonet
    labels:
      komodo.skip: # Prevent Komodo from stopping with StopAllContainers

  komodo-periphery:
    image: ghcr.io/mbecker20/periphery:latest
    container_name: komodo-periphery
    restart: unless-stopped
    env_file: .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /proc:/procs
      - ~/selfhosted/apps:/host/compose
    networks:
      - swarmnet
    labels:
      komodo.skip: # Prevent Komodo from stopping with StopAllContainers

networks:
  swarmnet:
    external: true
    driver: overlay
  komodonet: