services:
  uptime-kuma:
    image: louislam/uptime-kuma:1.23.13-alpine
    container_name: uptime-kuma
    restart: unless-stopped
    volumes:
      - ~/selfhosted/data/uptime-kuma:/app/data
    networks:
      - swarmnet # port 3001

networks:
  swarmnet:
    external: true
    driver: overlay