---
version: "3.9"

services:
  static-file-server:
    image: halverneus/static-file-server:v1.8.11
    container_name: static-file-server
    restart: unless-stopped
    volumes:
      - ./site:/web
    networks:
      - swarmnet # upstreams 8080

networks:
  swarmnet:
    external: true
    driver: overlay
