services:
  postgres:
    image: postgres:17-alpine
    container_name: ${CONTAINER_NAME} 
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=${PG_PASS}
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_DB=${PG_DB}
    volumes:
      - ~/selfhosted/data/postgres/${PG_DB}:/var/lib/postgresql/data
    networks:
      - swarmnet

networks:
  swarmnet:
    external: true
    driver: overlay