services:
  miniflux:
    image: miniflux/miniflux:2.1.3-distroless
    container_name: miniflux
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgres://miniflux:${POSTGRES_PASSWORD}@miniflux-db/miniflux?sslmode=disable
      - RUN_MIGRATIONS=1
      - CREATE_ADMIN=1
      - OAUTH2_PROVIDER=oidc
      - OAUTH2_USER_CREATION=1
    networks:
      - swarmnet # port 8080
      - miniflux-net
    depends_on:
      miniflux-db:
        condition: service_healthy

  miniflux-db:
    image: postgres:15
    container_name: miniflux-db
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - POSTGRES_USER=miniflux
      - POSTGRES_DB=miniflux
    volumes:
      - ~/selfhosted/data/miniflux:/var/lib/postgresql/data
    networks:
      - miniflux-net
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "miniflux"]
      interval: 10s
      start_period: 30s

networks:
  miniflux-net:
  swarmnet:
    external: true
    driver: overlay