---
version: "3"

services:
  miniflux:
    image: ghcr.io/miniflux/miniflux:2.0.44-distroless
    container_name: miniflux
    restart: unless-stopped
    labels:
      caddy: ${DOMAIN}
      caddy.reverse_proxy: "{{upstreams 8080}}"
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgres://miniflux:${POSTGRES_PASSWORD}@miniflux-db/miniflux?sslmode=disable
      - RUN_MIGRATIONS=1
      - CREATE_ADMIN=1
    networks:
      - cdp # upstreams 8080
    depends_on:
      miniflux-db:
        condition: service_healthy

  miniflux-db:
    image: postgres:15
    container_name: miniflux-db
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - POSTGRES_USER=miniflux
    volumes:
      - ~/selfhosted/data/miniflux:/var/lib/postgresql/data
    networks:
      - cdp
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "miniflux"]
      interval: 10s
      start_period: 30s

networks:
  cdp:
    external: true