services:
  synapse:
    image: ghcr.io/element-hq/synapse:latest
    container_name: synapse
    restart: unless-stopped
    environment:
      - SYNAPSE_REPORT_STATS=no
      - UID=1000
      - GID=1000
    volumes:
      - ~/selfhosted/data/synapse/appdata:/data
    depends_on:
      - synapse-db
    networks:
      - swarmnet # upstreams 8008

  synapse-db:
    image: docker.io/postgres:12-alpine
    container_name: synapse-db
    restart: unless-stopped
    env_file: .env
    environment:
      - POSTGRES_USER=synapse
      - POSTGRES_DB=synapse
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=C --lc-ctype=C
    volumes:
      - ~/selfhosted/data/synapse/db:/var/lib/postgresql/data
    networks:
      - swarmnet

  synapse-admin:
    image: awesometechnologies/synapse-admin
    container_name: synapse-admin
    restart: unless-stopped
    networks:
      - swarmnet # upstreams 80

networks:
  swarmnet:
    external: true
    driver: overlay